services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mapeia o arquivo de configuração
    ports:
      - "9090:9090"  # Expor a porta do Prometheus para o host
    restart: always
    networks:
      - metrics
    # environment:
    #   - PROMETHEUS_CONFIG=/etc/prometheus/prometheus.yml
networks:
  metrics:
    driver: bridge
