services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - metrics
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics
  
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   hostname: grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - metrics

networks:
  metrics:
    driver: bridge
