# global:
#     scrape_interval: 15s
#     # evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'app'
#     metrics_path: '/metrics'
#     static_configs:
#       # - targets: ['app:5000']
#       - targets: ['https://dockerized-prometheus-grafana.onrender.com/']
      
global:
    scrape_interval: 15s
    # evaluation_interval: 15s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['dockerized-prometheus-grafana.onrender.com']
